# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: streaming-pipeline-app
spec:
  selector:
    app: streaming-pipeline-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000